### ISSUE TITLE
add legal moves?

### ISSUE THREAD

**Issue by museum-future** [SteveBarnegren/SwiftChess#18]
Is there a painless way to display a green circle on the board  to show legal moves once a piece is touched?

**Comment by ghost** [comment]
@museum-future you can use my library to take a list of legal moves in given position: https://github.com/perechnev/ChessKit

**Comment by SteveBarnegren** [comment]
Hi @museum-future 

Yes, there is a method on `Board` called `possibleMoveLocationsForPiece(atLocation:)` which returns an array of `BoardLocation`s.

Here is a code snippet from my own chess game:

```
if let selectedIndex = selectedIndex {
  let selectedLocation = BoardLocation(index: selectedIndex)
  boardView.possibleMovesView.locations = game.board.possibleMoveLocationsForPiece(atLocation: selectedLocation)
}
```

Hope that helps!
