### ISSUE TITLE
How strong the engine is?

### ISSUE THREAD

**Issue by ghost** [SteveBarnegren/SwiftChess#19]
Hello @SteveBarnegren ! I would like to ask you about how strong your engine is? Have you ever made a bot on Lichess to estimate the rating?

**Comment by SteveBarnegren** [comment]
The engine isn't bad. It can certainly beat a novice player, but a seasoned chess player would probably not find it to be a worthy opponent.

It certainly can't play anywhere near the level of engines such as [Stockfish](https://stockfishchess.org/), which would probably be a good choice if you are looking to utilise a really challenging chess AI.

That said, I do get a lot of positive feedback about my own chess app that is powered by SwiftChess. I think part of the reason that you might choose to use it is for the ease of integration for a Swift developer, and that it's approachable in terms of being able to understand and modify the engine for your own purposes.
