### ISSUE TITLE
Levels

### ISSUE THREAD

**Issue by rasIOS** [SteveBarnegren/SwiftChess#6]
Hi,
How can we change **Game levels**?
Like easy, Medium, Hard.
Please tell us.

Thanks lot.

**Comment by SteveBarnegren** [comment]
Hi @rasIOS 

When creating an `AIPlayer` you can pass in an `AIConfiguration` struct. Pass in the difficulty when creating the `AIConfiguration`, you can use `.easy`, `.medium` or `.hard`.

For instance, you can create a `hard` difficulty AI player like this:

```
let configuration = AIConfiguration(difficulty: .hard)
let player = AIPlayer(color: .black, configuration: configuration)
```

**Comment by rasIOS** [comment]
It's work thanks :)
