### ISSUE TITLE
Multi player

### ISSUE THREAD

**Issue by rasIOS** [SteveBarnegren/SwiftChess#7]
Hi
How can we code multi player for this game?
(Two Phones).

**Comment by SteveBarnegren** [comment]
Hey @rasIOS 

There's two approaches to this. The first is to send the move that you make to the other phone, and keep updating the boards to keep them in sync.

The other way that you can achieve this is to package up the whole game state and send it to the other phone. Have a look at the [persistence section of the readme](https://github.com/SteveBarnegren/SwiftChess#persistence) which shows you how you can convert a game to and from a dictionary. You could then serialise this to Json and send it to the other device. The other device can then recreate the whole game state by initialising a new game with that dictionary.

There's no networking included in SwiftChess, but you should be able to send data between players using something like [GameKit](https://developer.apple.com/documentation/gamekit).
