### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by rasIOS** [SteveBarnegren/SwiftChess#8]
Hi
Can you please add a timer for the chess board?

Really appreciate your work.

thanks

**Comment by SteveBarnegren** [comment]
Hi @rasIOS 

Can you explain a little more what you're looking for? If you're looking to time how long the game has been active, or how long the player's is taking to decide their move, it's probably better to implement that functionality in the host app rather than in SwiftChess

**Comment by SteveBarnegren** [comment]
Closing due to no response
