### ISSUE TITLE
App is crashing when I navigate back to MenuViewController.

### ISSUE THREAD

**Issue by SuneelGunupudi** [SteveBarnegren/SwiftChess#9]
AI and AI player mode, app is crashing when I navigate back to MenuViewController. How to stop the AI action when the ViewController dismiss.

**Comment by SteveBarnegren** [comment]
Hi @SuneelGunupudi - Sorry this has taken me such a long time to get around to, but better late than never!

I've fixed this now, in version 1.1.2.
